workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      vars:
        NODE_ENV: production
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android Release APK
        script: |
          npm run android:assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com

